"""QC-SCM Detection Service API with multi-session support."""

import asyncio
import base64
import hashlib
import hmac
import json
import logging
import re
import time
from pathlib import Path
from typing import Any, Dict, List, Optional, Union, Set

import yaml
import cv2

# Base path: Boxes/flow (parent of api/)
_base_flow = Path(__file__).resolve().parent.parent

from core.device_manager import select_device
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import StreamingResponse
from pydantic import BaseModel

from core.model_loader import ModelLoader
from core.firebase_client import initialize as init_firebase
from core.pipeline_manager import PipelineManager
from core.session_manager import SessionManager

# Setup logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s %(message)s",
    datefmt="%H:%M:%S",
)
logger = logging.getLogger(__name__)


def _get_cors_config() -> tuple:
    """
    Load CORS config. Returns (allow_origins, allow_credentials).
    - If config/app.yaml has cors_origins (non-empty list): use those with credentials=True.
    - Else: use ["*"] with credentials=False (works for localhost, LAN, remote out-of-the-box).
    """
    base = _base_flow
    app_cfg_path = base / "config" / "app.yaml"
    if app_cfg_path.exists():
        try:
            with open(app_cfg_path) as f:
                app_cfg = yaml.safe_load(f) or {}
            origins = app_cfg.get("cors_origins")
            if origins and isinstance(origins, list) and len(origins) > 0:
                cleaned = [str(o).rstrip("/") for o in origins if o]
                if cleaned:
                    return cleaned, True
        except Exception:  # noqa: S110
            pass
    return ["*"], False


# FastAPI app
app = FastAPI(
    title="QC-SCM Detection Service",
    description="Multi-session quality control detection with defect analysis",
    version="1.0.0",
)

_cors_origins, _cors_credentials = _get_cors_config()
app.add_middleware(
    CORSMiddleware,
    allow_origins=_cors_origins,
    allow_credentials=_cors_credentials,
    allow_methods=["GET", "POST", "PUT", "DELETE", "OPTIONS"],
    allow_headers=["*"],
    expose_headers=["*"],
)

# Global state
session_manager = SessionManager.get_instance()
configs: Dict[str, Any] = {}


# -----------------------------------------------------------------------------
# Schema models
class OpenReportRequest(BaseModel):
    """Request body for POST /api/reports/open. report_id is generated by the frontend."""

    report_id: str
    camera_source: Union[str, int]
    production_line_id: Optional[str] = None
    target_speed: int
    max_temp: int
    max_amps: int


class CloseReportRequest(BaseModel):
    """Request body for POST /api/reports/close."""

    report_id: str


class ReportResponse(BaseModel):
    """Response for report mutation endpoints."""

    status: str
    report_id: str
    message: str


class ReportSummary(BaseModel):
    """Single active report summary for GET /api/reports."""

    report_id: str
    viewers_count: int


class HealthResponse(BaseModel):
    """Response for health check endpoint."""

    status: str
    active_reports: int


def _production_line_from_camera_source(camera_source: Union[str, int]) -> str:
    """
    Derive a stable production_line_id from camera_source when the client does not send one.

    Rules:
    - Numeric source 0 -> line-1, 1 -> line-2, etc.
    - /dev/videoN -> line-(N+1)
    - Other sources -> line-<normalized_source> (fallback to short hash if needed)
    """
    if isinstance(camera_source, int):
        return f"line-{camera_source + 1}"

    source_str = str(camera_source).strip()
    if source_str.isdigit():
        return f"line-{int(source_str) + 1}"

    m = re.search(r"/dev/video(\d+)$", source_str)
    if m:
        return f"line-{int(m.group(1)) + 1}"

    normalized = re.sub(r"[^a-zA-Z0-9]+", "-", source_str).strip("-").lower()
    if normalized:
        return f"line-{normalized}"

    digest = hashlib.sha1(source_str.encode("utf-8")).hexdigest()[:8]
    return f"line-{digest}"


# -----------------------------------------------------------------------------
# Configuration loading
def _load_configs(base: Path) -> None:
    """Load all YAML configs from the single config/ directory."""
    cfg = base / "config"

    # app.yaml is optional (CORS); webrtc.yaml is required (runtime config, not committed)
    app_path = cfg / "app.yaml"
    if app_path.exists():
        with open(app_path) as f:
            configs["app"] = yaml.safe_load(f) or {}
    else:
        configs["app"] = {}

    webrtc_path = cfg / "webrtc.yaml"
    if webrtc_path.exists():
        with open(webrtc_path) as f:
            configs["webrtc"] = yaml.safe_load(f) or {}
    else:
        configs["webrtc"] = {}

    # Service configs (now co-located in config/ alongside environment configs)
    with open(cfg / "box_detector.yaml") as f:
        configs["box"] = yaml.safe_load(f)
    with open(cfg / "defect_detector.yaml") as f:
        configs["defect"] = yaml.safe_load(f)
    with open(cfg / "stream.yaml") as f:
        configs["stream"] = yaml.safe_load(f)
    with open(cfg / "firebase.yaml") as f:
        configs["firebase"] = yaml.safe_load(f)

    # Ensure stability config
    if "stability" not in configs["defect"]:
        configs["defect"]["stability"] = {
            "min_frames": 4,
            "max_missed": 6,
            "vote_window": 9,
            "vote_threshold": 5,
            "early_detection_frames": 3,
            "track_grace_frames": 3,
            "recent_track_max_age": 15,
            "recovery_iou_threshold": 0.4,
        }
    # Ensure tracking config
    if "tracking" not in configs["defect"]:
        configs["defect"]["tracking"] = {
            "iou_threshold": 0.35,
            "bbox_smooth_alpha": 0.6,
        }
    # Ensure rendering config
    if "rendering" not in configs["defect"]:
        configs["defect"]["rendering"] = {
            "visibility_threshold": 0.2,
        }

    # Resolve device once for both detectors (config -> QC_SCM_FLOW_DEVICE -> auto)
    raw_device = configs.get("box", {}).get("device", "0")
    resolved_device = select_device(
        str(raw_device).strip() or None,
        context="flow",
    )
    configs["box"]["device"] = resolved_device
    configs["defect"]["device"] = resolved_device

    # Initialize Firebase Realtime Database (credentials + database URL from config/env)
    fb_cfg = configs["firebase"]
    cred_rel = (
        fb_cfg.get("service_account_path")
        or fb_cfg.get("credentials_path")
        or "firebase-service-account.json"
    )
    cred_path = base / "config" / cred_rel

    # database_url: firebase.yaml first, then firebase_config.json (both in config/)
    database_url = str(fb_cfg.get("database_url", "")).strip()
    if not database_url:
        config_json_path = base / "config" / "firebase_config.json"
        if config_json_path.exists():
            with open(config_json_path) as f:
                fb_secrets = json.load(f)
                database_url = (
                    fb_secrets.get("FIREBASE_DATABASE_URL")
                    or fb_secrets.get("database_url")
                    or ""
                ).strip()
    if not database_url:
        raise ValueError(
            "Firebase Realtime Database URL must be set in config: "
            "firebase.yaml (database_url) or firebase_config.json (see firebase_config.json.example)."
        )
    init_firebase(str(cred_path), database_url)


def _resolve_existing_path(base: Path, configured_path: str) -> str:
    """
    Resolve a configured path against common roots and return first existing path.

    Supports:
    - absolute paths
    - paths relative to `Boxes/flow`
    - paths relative to repo root (parent of `Boxes/`)
    """
    p = Path(configured_path)
    if p.is_absolute():
        return str(p)

    candidates = [
        base / p,         # flow-relative
        base.parent / p,  # Boxes-relative
        base.parent.parent / p,  # repo-root-relative
    ]
    for candidate in candidates:
        if candidate.exists():
            return str(candidate)

    # Preserve previous behavior as final fallback for clearer error context upstream.
    return str(base / p)


@app.on_event("startup")
async def startup_event() -> None:
    """Initialize configs, models, and Firebase client."""
    base = _base_flow
    try:
        _load_configs(base)
        model_loader = ModelLoader.get_instance()
        box_path = _resolve_existing_path(base, str(configs["box"]["model_path"]))
        defect_path = _resolve_existing_path(base, str(configs["defect"]["model_path"]))
        model_loader.load_models(box_path, defect_path)
        device = str(configs.get("box", {}).get("device", "0"))
        model_loader.warmup(device=device)
        logger.info("[Service] QC-SCM Detection Service started")
    except Exception as e:
        logger.error("[Error] startup failed: %s", e, exc_info=True)
        raise


@app.on_event("shutdown")
async def shutdown_event() -> None:
    """Clean up pipeline manager workers."""
    PipelineManager.get_instance().shutdown()
    logger.info("[Service] shutdown")


# -----------------------------------------------------------------------------
# API Endpoints
@app.post("/api/reports/open", response_model=ReportResponse)
async def open_report(body: OpenReportRequest) -> ReportResponse:
    """Open a new headless detection report. report_id is generated by the frontend."""
    resolved_production_line_id = (
        body.production_line_id.strip()
        if body.production_line_id and body.production_line_id.strip()
        else _production_line_from_camera_source(body.camera_source)
    )

    logger.info("=" * 60)
    logger.info("OPEN SESSION START")
    logger.info("Request Context:")
    logger.info("  - report_id:          %s", body.report_id)
    logger.info("  - session_id:         %s", body.report_id)  # report_id acts as session_id
    logger.info("  - production_line_id: %s", resolved_production_line_id)
    logger.info("  - camera_source:      %s", body.camera_source)
    logger.info("  - target_speed:       %s", body.target_speed)
    logger.info("  - max_temp:           %s", body.max_temp)
    logger.info("  - max_amps:           %s", body.max_amps)
    logger.info("=" * 60)
    
    try:
        loop = asyncio.get_running_loop()

        worker = session_manager.create_session(
            report_id=body.report_id,
            camera_source=body.camera_source,
            production_line_id=resolved_production_line_id,
            target_speed=body.target_speed,
            max_temp=body.max_temp,
            max_amps=body.max_amps,
            box_cfg=configs["box"],
            defect_cfg=configs["defect"],
            stream_cfg=configs["stream"],
            app_cfg=configs["app"],
            loop=loop,
        )
        return ReportResponse(
            status="success",
            report_id=worker.report_id,
            message=f"Report started with camera {body.camera_source}",
        )
    except ValueError as e:
        logger.warning("[Error] open report failed: %s", e)
        raise HTTPException(status_code=400, detail=str(e))
    except Exception as e:
        logger.exception("[Error] open report")
        raise HTTPException(status_code=500, detail="Internal server error")


@app.post("/api/reports/close", response_model=ReportResponse)
async def close_report(body: CloseReportRequest) -> ReportResponse:
    """Close an active detection report by report_id."""
    try:
        closed, already_closed = session_manager.close_session(body.report_id)
        if already_closed:
            return ReportResponse(
                status="success",
                report_id=body.report_id,
                message="Report is already closed",
            )
        return ReportResponse(
            status="success",
            report_id=body.report_id,
            message="Report closed successfully",
        )
    except HTTPException:
        raise
    except Exception as e:
        logger.exception("[Error] close report")
        raise HTTPException(status_code=500, detail="Internal server error")


@app.get("/api/reports", response_model=List[ReportSummary])
async def list_reports() -> List[ReportSummary]:
    """List only currently active (open) reports. Format: report_id, viewers_count."""
    try:
        sessions = session_manager.list_active_sessions()
        return [ReportSummary(**s) for s in sessions]
    except Exception as e:
        logger.exception("[Error] list reports")
        raise HTTPException(status_code=500, detail="Internal server error")


@app.get("/api/health", response_model=HealthResponse)
async def health_check() -> HealthResponse:
    """Service health and active report count."""
    try:
        active = len(session_manager.list_active_sessions())
        return HealthResponse(status="healthy", active_reports=active)
    except Exception as e:
        logger.exception("[Error] health check")
        raise HTTPException(status_code=500, detail="Internal server error")


# -----------------------------------------------------------------------------
# MJPEG Streaming
# -----------------------------------------------------------------------------

async def generate_mjpeg_stream(report_id: str):
    """Generator for MJPEG stream."""
    manager = PipelineManager.get_instance()
    while True:
        frame = manager.get_latest_frame(report_id)
        if frame is not None:
            ret, buffer = cv2.imencode('.jpg', frame)
            if ret:
                yield (b'--frame\r\n'
                       b'Content-Type: image/jpeg\r\n\r\n' + buffer.tobytes() + b'\r\n')
        
        # Limit frame rate to ~30 FPS to save bandwidth/CPU
        await asyncio.sleep(0.033)


@app.get("/video_feed")
async def video_feed(report_id: str):
    """Serve the annotated canvas through MJPEG."""
    # Verify session exists
    if not session_manager.get_session(report_id):
        raise HTTPException(status_code=404, detail="Session not found")
        
    return StreamingResponse(
        generate_mjpeg_stream(report_id),
        media_type="multipart/x-mixed-replace; boundary=frame"
    )


@app.get("/api/config")
async def get_client_config() -> Dict[str, Any]:
    """
    Returns empty WebRTC config as it's no longer used, 
    maintained for frontend compatibility if needed.
    """
    return {"webrtc": {"mode": "mjpeg"}}

