"""QC-SCM Detection Service API with multi-session support."""

import asyncio
import base64
import hashlib
import hmac
import json
import logging
import os
import time
from pathlib import Path
from typing import Any, Dict, List, Optional, Union, Set

import yaml
from dotenv import load_dotenv

# Base path: Boxes/flow (parent of api/)
_base_flow = Path(__file__).resolve().parent.parent
_repo_root = _base_flow.parent.parent
# Load environment secrets: Boxes/flow/config/.env then flow dir .env then repo root .env then cwd
load_dotenv(_base_flow / "config" / ".env")
load_dotenv(_base_flow / ".env")
load_dotenv(_repo_root / ".env")
load_dotenv()

from core.device_manager import select_device
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

from aiortc import (
    RTCPeerConnection,
    RTCSessionDescription,
    RTCConfiguration,
    RTCIceServer,
)

from core.model_loader import ModelLoader
from core.firebase_client import initialize as init_firebase
from core.pipeline_manager import PipelineManager
from core.session_manager import SessionManager
from core.webrtc_track import VideoTransformTrack

# Setup logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s %(message)s",
    datefmt="%H:%M:%S",
)
logger = logging.getLogger(__name__)


def _get_cors_config() -> tuple:
    """
    Load CORS config. Returns (allow_origins, allow_credentials).
    - If config/app.yaml has cors_origins (non-empty list): use those with credentials=True.
    - Else: use ["*"] with credentials=False (works for localhost, LAN, remote out-of-the-box).
    """
    base = _base_flow
    app_cfg_path = base / "config" / "app.yaml"
    if app_cfg_path.exists():
        try:
            with open(app_cfg_path) as f:
                app_cfg = yaml.safe_load(f) or {}
            origins = app_cfg.get("cors_origins")
            if origins and isinstance(origins, list) and len(origins) > 0:
                cleaned = [str(o).rstrip("/") for o in origins if o]
                if cleaned:
                    return cleaned, True
        except Exception:  # noqa: S110
            pass
    return ["*"], False


# FastAPI app
app = FastAPI(
    title="QC-SCM Detection Service",
    description="Multi-session quality control detection with defect analysis",
    version="1.0.0",
)

_cors_origins, _cors_credentials = _get_cors_config()
app.add_middleware(
    CORSMiddleware,
    allow_origins=_cors_origins,
    allow_credentials=_cors_credentials,
    allow_methods=["GET", "POST", "PUT", "DELETE", "OPTIONS"],
    allow_headers=["*"],
    expose_headers=["*"],
)

# Global state
session_manager = SessionManager.get_instance()
configs: Dict[str, Any] = {}

# WebRTC Peer Connections
pcs: Set[RTCPeerConnection] = set()


# -----------------------------------------------------------------------------
# Schema models
class OpenReportRequest(BaseModel):
    """Request body for POST /api/reports/open. report_id is generated by the frontend."""

    report_id: str
    camera_source: Union[str, int]
    production_line_id: str


class CloseReportRequest(BaseModel):
    """Request body for POST /api/reports/close."""

    report_id: str


class ReportResponse(BaseModel):
    """Response for report mutation endpoints."""

    status: str
    report_id: str
    message: str


class ReportSummary(BaseModel):
    """Single active report summary for GET /api/reports."""

    report_id: str
    viewers_count: int


class HealthResponse(BaseModel):
    """Response for health check endpoint."""

    status: str
    active_reports: int


class OfferRequest(BaseModel):
    """WebRTC Offer request. report_id identifies the active report."""
    sdp: str
    type: str
    report_id: str


class OfferResponse(BaseModel):
    """WebRTC Answer response."""
    sdp: str
    type: str


# -----------------------------------------------------------------------------
# Configuration loading
def _load_configs(base: Path) -> None:
    """Load all YAML configs from the single config/ directory."""
    cfg = base / "config"

    # Environment-dependent config (optional, with defaults)
    # Note: api.yaml is loaded by main.py only; webrtc used here for ICE
    for key, filename in [("app", "app.yaml"), ("webrtc", "webrtc.yaml")]:
        path = cfg / filename
        if path.exists():
            with open(path) as f:
                configs[key] = yaml.safe_load(f) or {}
        else:
            configs[key] = {}
    # Defaults when webrtc.yaml is missing (e.g. not committed; use env TURN_SECRET or add webrtc.yaml)
    if "webrtc" not in configs or not configs["webrtc"]:
        configs["webrtc"] = {
            "stun": {"urls": "stun:20.51.117.96:3478"},
            "turn": {"urls": "turn:20.51.117.96:3478", "secret": os.environ.get("TURN_SECRET", "")},
        }

    # Service configs (now co-located in config/ alongside environment configs)
    with open(cfg / "box_detector.yaml") as f:
        configs["box"] = yaml.safe_load(f)
    with open(cfg / "defect_detector.yaml") as f:
        configs["defect"] = yaml.safe_load(f)
    with open(cfg / "stream.yaml") as f:
        configs["stream"] = yaml.safe_load(f)
    with open(cfg / "firebase.yaml") as f:
        configs["firebase"] = yaml.safe_load(f)

    # Ensure stability config
    if "stability" not in configs["defect"]:
        configs["defect"]["stability"] = {
            "min_frames": 4,
            "max_missed": 6,
            "vote_window": 9,
            "vote_threshold": 5,
            "early_detection_frames": 3,
            "track_grace_frames": 3,
            "recent_track_max_age": 15,
            "recovery_iou_threshold": 0.4,
        }
    # Ensure tracking config
    if "tracking" not in configs["defect"]:
        configs["defect"]["tracking"] = {
            "iou_threshold": 0.35,
            "bbox_smooth_alpha": 0.6,
        }
    # Ensure rendering config
    if "rendering" not in configs["defect"]:
        configs["defect"]["rendering"] = {
            "visibility_threshold": 0.2,
        }

    # Resolve device once for both detectors (config -> QC_SCM_FLOW_DEVICE -> auto)
    raw_device = configs.get("box", {}).get("device", "0")
    resolved_device = select_device(
        str(raw_device).strip() or None,
        env_var="QC_SCM_FLOW_DEVICE",
        context="flow",
    )
    configs["box"]["device"] = resolved_device
    configs["defect"]["device"] = resolved_device

    # Initialize Firebase Realtime Database (credentials + database URL from config/env)
    fb_cfg = configs["firebase"]
    cred_rel = (
        fb_cfg.get("service_account_path")
        or fb_cfg.get("credentials_path")
        or "firebase-service-account.json"
    )
    cred_path = base / "config" / cred_rel

    # Prefer database_url from firebase.yaml, then env, then firebase_config.json
    database_url = str(fb_cfg.get("database_url", "")).strip()
    if not database_url:
        database_url = os.environ.get("FIREBASE_DATABASE_URL", "").strip()
    if not database_url:
        config_json_path = base / "config" / "firebase_config.json"
        if config_json_path.exists():
            with open(config_json_path) as f:
                fb_secrets = json.load(f)
                database_url = (
                    fb_secrets.get("FIREBASE_DATABASE_URL")
                    or fb_secrets.get("database_url")
                    or ""
                ).strip()
    if not database_url:
        raise ValueError(
            "Firebase Realtime Database URL must be set. Use firebase.yaml (database_url), "
            "Boxes/flow/config/.env, or firebase_config.json (see Boxes/flow/config/.env.example)."
        )
    init_firebase(str(cred_path), database_url)


@app.on_event("startup")
async def startup_event() -> None:
    """Initialize configs, models, and Firebase client."""
    base = _base_flow
    try:
        _load_configs(base)
        model_loader = ModelLoader.get_instance()
        box_path = configs["box"]["model_path"]
        defect_path = configs["defect"]["model_path"]
        if not Path(box_path).is_absolute():
            box_path = str(base / box_path)
        if not Path(defect_path).is_absolute():
            defect_path = str(base / defect_path)
        model_loader.load_models(box_path, defect_path)
        device = str(configs.get("box", {}).get("device", "0"))
        model_loader.warmup(device=device)
        logger.info("[Service] QC-SCM Detection Service started")
    except Exception as e:
        logger.error("[Error] startup failed: %s", e, exc_info=True)
        raise


@app.on_event("shutdown")
async def shutdown_event() -> None:
    """Clean up WebRTC connections and pipeline manager workers."""
    PipelineManager.get_instance().shutdown()
    coros = [pc.close() for pc in pcs]
    await asyncio.gather(*coros)
    pcs.clear()
    logger.info("[Service] shutdown")


# -----------------------------------------------------------------------------
# API Endpoints
@app.post("/api/reports/open", response_model=ReportResponse)
async def open_report(body: OpenReportRequest) -> ReportResponse:
    """Open a new headless detection report. report_id is generated by the frontend."""
    try:
        loop = asyncio.get_running_loop()

        worker, already_open = session_manager.create_session(
            report_id=body.report_id,
            camera_source=body.camera_source,
            production_line_id=body.production_line_id,
            box_cfg=configs["box"],
            defect_cfg=configs["defect"],
            stream_cfg=configs["stream"],
            loop=loop,
        )
        report_id = worker.report_id
        if already_open:
            return ReportResponse(
                status="success",
                report_id=report_id,
                message="Report is already open for this production line",
            )
        return ReportResponse(
            status="success",
            report_id=report_id,
            message=f"Report started with camera {body.camera_source}",
        )
    except ValueError as e:
        logger.warning("[Error] open report failed: %s", e)
        raise HTTPException(status_code=400, detail=str(e))
    except Exception as e:
        logger.exception("[Error] open report")
        raise HTTPException(status_code=500, detail="Internal server error")


@app.post("/api/reports/close", response_model=ReportResponse)
async def close_report(body: CloseReportRequest) -> ReportResponse:
    """Close an active detection report by report_id."""
    try:
        closed, already_closed = session_manager.close_session(body.report_id)
        if already_closed:
            return ReportResponse(
                status="success",
                report_id=body.report_id,
                message="Report is already closed",
            )
        return ReportResponse(
            status="success",
            report_id=body.report_id,
            message="Report closed successfully",
        )
    except HTTPException:
        raise
    except Exception as e:
        logger.exception("[Error] close report")
        raise HTTPException(status_code=500, detail="Internal server error")


@app.get("/api/reports", response_model=List[ReportSummary])
async def list_reports() -> List[ReportSummary]:
    """List only currently active (open) reports. Format: report_id, viewers_count."""
    try:
        sessions = session_manager.list_active_sessions()
        return [ReportSummary(**s) for s in sessions]
    except Exception as e:
        logger.exception("[Error] list reports")
        raise HTTPException(status_code=500, detail="Internal server error")


@app.get("/api/health", response_model=HealthResponse)
async def health_check() -> HealthResponse:
    """Service health and active report count."""
    try:
        active = len(session_manager.list_active_sessions())
        return HealthResponse(status="healthy", active_reports=active)
    except Exception as e:
        logger.exception("[Error] health check")
        raise HTTPException(status_code=500, detail="Internal server error")


def _generate_turn_credentials(secret: str) -> tuple[str, str]:
    """Generate temporary TURN credentials using REST API authentication (valid for 5 mins)."""
    expiry = int(time.time()) + 300
    username = f"{expiry}:stream"

    digest = hmac.new(
        secret.encode(),
        username.encode(),
        hashlib.sha1
    ).digest()

    credential = base64.b64encode(digest).decode()
    return username, credential


def _ice_servers_for_mode(mode: str, for_aiortc: bool = False) -> list:
    """
    Build ICE server list from webrtc_mode.
    - auto:   host + STUN + TURN
    - direct: host only (empty list)
    - stun:   host + STUN
    - relay:  host + TURN only
    When for_aiortc=False (client config), includes temporary TURN username/credential
    (short-lived, e.g. 5 minutes) so the browser can establish WebRTC connections.
    """
    w = configs.get("webrtc") or {}
    stun = w.get("stun") or {}
    turn = w.get("turn") or {}
    ice_servers: list = []
    if mode == "direct":
        return ice_servers
    if mode in ("auto", "stun") and stun.get("urls"):
        urls = stun["urls"] if isinstance(stun["urls"], str) else stun["urls"]
        ice_servers.append(RTCIceServer(urls=urls) if for_aiortc else {"urls": urls})
    if mode in ("auto", "relay") and turn.get("urls") and turn.get("secret"):
        username, credential = _generate_turn_credentials(turn["secret"])
        urls = turn["urls"] if isinstance(turn["urls"], str) else turn["urls"]
        if for_aiortc:
            ice_servers.append(RTCIceServer(urls=urls, username=username, credential=credential))
        else:
            ice_servers.append({"urls": urls, "username": username, "credential": credential})
    return ice_servers


def _client_webrtc_config() -> Dict[str, Any]:
    """
    Build client WebRTC config: STUN servers, TURN servers, and temporary TURN
    credentials (short-lived, valid for a few minutes). The frontend uses this
    to create RTCPeerConnection and establish WebRTC connections.
    """
    w = configs.get("webrtc") or {}
    mode = (w.get("webrtc_mode") or "auto").strip().lower() or "auto"
    if mode not in ("auto", "direct", "stun", "relay"):
        mode = "auto"
    ice_servers = _ice_servers_for_mode(mode, for_aiortc=False)
    logger.debug("WebRTC config: webrtc_mode=%s, ice_servers=%d", mode, len(ice_servers))
    return {
        "webrtc": {
            "iceServers": ice_servers,
            "webrtc_mode": mode,
        }
    }


@app.get("/api/config")
async def get_client_config() -> Dict[str, Any]:
    """
    Client configuration for WebRTC: STUN servers, TURN servers, and temporary
    TURN credentials (time-limited, e.g. 5 minutes). The frontend retrieves this
    to configure RTCPeerConnection and establish WebRTC connections.
    """
    return _client_webrtc_config()


@app.post("/webrtc/offer", response_model=OfferResponse)
async def webrtc_offer(params: OfferRequest) -> OfferResponse:
    """
    Handle WebRTC SDP offer and establish connection.
    Attach the detection stream as a video track. report_id must match an open report.
    """
    worker = session_manager.get_session(params.report_id)
    if worker is None:
        raise HTTPException(status_code=404, detail="Session not found")

    offer = RTCSessionDescription(sdp=params.sdp, type=params.type)

    w = configs.get("webrtc") or {}
    mode = (w.get("webrtc_mode") or "auto").strip().lower() or "auto"
    if mode not in ("auto", "direct", "stun", "relay"):
        mode = "auto"
    ice_servers = _ice_servers_for_mode(mode, for_aiortc=True)
    config = RTCConfiguration(iceServers=ice_servers)
    pc = RTCPeerConnection(configuration=config)
    pcs.add(pc)

    def _log_ice_candidates() -> None:
        """Log gathered ICE candidates with type (host, srflx, relay) for debugging."""
        try:
            ice_transport = None
            if getattr(pc, "sctp", None) and getattr(pc.sctp, "transport", None):
                dtls = pc.sctp.transport
                ice_transport = getattr(dtls, "transport", None)
            if ice_transport is None:
                for transceiver in pc.getTransceivers():
                    sender = getattr(transceiver, "sender", None)
                    dtls = getattr(sender, "transport", None) if sender else None
                    if dtls and getattr(dtls, "transport", None):
                        ice_transport = dtls.transport
                        break
            if ice_transport and hasattr(ice_transport, "iceGatherer"):
                gatherer = ice_transport.iceGatherer
                if hasattr(gatherer, "getLocalCandidates"):
                    for c in gatherer.getLocalCandidates():
                        ctype = getattr(c, "type", "unknown")
                        logger.debug("ICE candidate gathered: type=%s", ctype)
        except Exception as e:
            logger.debug("ICE candidate logging skipped: %s", e)

    @pc.on("icegatheringstatechange")
    async def on_icegatheringstatechange():
        if pc.iceGatheringState == "complete":
            _log_ice_candidates()

    async def _log_selected_transport() -> None:
        """
        Log a single clean line indicating how WebRTC connected:
        - direct (host/srflx)
        - turn-relay (relay)

        Primary method uses aiortc's selected ICE candidate pair from the
        underlying iceTransport. Falls back to 'unknown' on error.
        """
        transport = "unknown"
        try:
            ice_transport = None

            # Prefer SCTP transport (if datachannel present)
            if getattr(pc, "sctp", None) and getattr(pc.sctp, "transport", None):
                dtls = pc.sctp.transport
                ice_transport = getattr(dtls, "transport", None)

            # Fallback: inspect sender transports if SCTP is not available
            if ice_transport is None:
                for transceiver in pc.getTransceivers():
                    sender = getattr(transceiver, "sender", None)
                    dtls = getattr(sender, "transport", None) if sender else None
                    if dtls and getattr(dtls, "transport", None):
                        ice_transport = dtls.transport
                        break

            if ice_transport and hasattr(ice_transport, "getSelectedCandidatePair"):
                pair = ice_transport.getSelectedCandidatePair()
                if pair:
                    local_type = getattr(pair.local, "type", None)
                    remote_type = getattr(pair.remote, "type", None)
                    if local_type == "relay" or remote_type == "relay":
                        transport = "relay"
                    elif local_type == "srflx" or remote_type == "srflx":
                        transport = "stun"
                    else:
                        transport = "direct"

        except Exception as e:
            logger.debug("WebRTC transport detection failed: %s", e)

        logger.info("[WebRTC] connected (%s)", transport)

    logger.info("[WebRTC] connecting")

    @pc.on("connectionstatechange")
    async def on_connectionstatechange():
        state = pc.connectionState
        if state == "connected":
            await _log_selected_transport()
        elif state in {"failed", "disconnected", "closed"}:
            logger.info("[WebRTC] %s", state)
        if state == "failed":
            await pc.close()
            pcs.discard(pc)
        elif state == "closed":
            pcs.discard(pc)

    video_track = VideoTransformTrack()
    worker.add_track(video_track)

    @pc.on("track")
    def on_track(track):
        # We don't handle incoming tracks (audio/video from client)
        pass

    # We add track to PC to send video to client
    pc.addTrack(video_track)

    # Handle cleanup when PC closes
    # We can't easily hook into pc.close() here, but connectionstatechange helps.
    # More robustly, we should remove the track from worker when PC is closed.
    # But for now, we rely on connectionstatechange.
    orig_close = pc.close
    async def new_close():
        worker.remove_track(video_track)
        await orig_close()
    pc.close = new_close

    try:
        await pc.setRemoteDescription(offer)
        answer = await pc.createAnswer()
        await pc.setLocalDescription(answer)

        return OfferResponse(
            sdp=pc.localDescription.sdp,
            type=pc.localDescription.type
        )
    except Exception as e:
        logger.error("[Error] WebRTC offer failed: %s", e)
        # Cleanup
        worker.remove_track(video_track)
        await pc.close()
        pcs.discard(pc)
        raise HTTPException(status_code=500, detail=str(e))
